#!/usr/bin/python3

import db
from algonquin import make_token, make_token_url, config

u = db.User(email  = config['sysop_email'],
            handle = config['sysop_handle'],
            portrait = config['default_portrait'])
u.save()

token = make_token(u)
url   = make_token_url(token)

s = db.Session(user      = u.id,
               sessionid = token)
s.save()

for room in config['public_rooms']:
    r = db.Room(owner  = u.id,
                public = True,
                name   = room)
    r.save()

u.join_public()
u.commit()

print("Database Created.")
print("login url: "+url)
