---
- hosts: all
  vars:
    local_user: dave
    chat_hostname: orgone
    chat_fqdn: orgone.institute
    chat_fqdntwo: www.orgone.institute
  remote_user: root

  tasks:
  - name: Upgrade the OS (apt-get dist-upgrade)
    apt:
      upgrade: dist

  - name: Run the equivalent of "apt-get update" as a separate step
    apt:
      update_cache: yes

  - name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: ensure apt packages are installed
    apt:
      pkg:
      - nginx
      - snap
      - git
      - python3-pip
      - gunicorn3
      
  - name: install pip packagees
    pip:
      executable: pip3
      name:
        - flask
        - flask-socketio
        - passlib
        - eventlet

#  - name: install snap core
#    community.general.snap:
#      name: core

# - name: install certbot
#   community.general.snap:
#     name: certbot
#     classic: yes

  - name: Add algonquin user
    user:
      name: algonquin

  - name: write the nginx config file
    template:
      src: nginx/default
      dest: /etc/nginx/sites-available/default

  - name: write the gunicorn service file
    template:
      src: nginx/gunicorn.service
      dest: /etc/systemd/system/gunicorn.service

  - name: write the gunicorn socket file
    template:
      src: nginx/gunicorn.socket
      dest: /etc/systemd/system/gunicorn.socket

# - name: symlink for certbot on path
#   file:
#     src: /snap/bin/certbot
#     dest: /usr/bin/certbot
#     owner: root
#     group: root
#     state: link
  
  - name: get algonquin
    git:
      repo: 'https://github.com/Dav3xor/algonquin.git'
      dest: /home/algonquin/algonquin
    become: yes
    become_user: algonquin

  - name: set algonquin permissions
    file:
      dest: /home/algonquin/algonquin
      owner: algonquin
      group: algonquin
      recurse: yes

  - name: symlink nginx config
    file:
      src: /etc/nginx/sites-available/default
      dest: /etc/nginx/sites-enabled/default
      owner: root
      group: root
      state: link
  
  - name: restart nginx
    systemd:
      state: restarted
      daemon_reload: yes
      name: nginx

  - name: restart gunicorn
    systemd:
      state: restarted
      daemon_reload: yes
      name: gunicorn
