#!/usr/bin/python3

import tables
from algonquin import config

u = tables.User(email  = config['sysop_email'],
                handle = config['sysop_handle'],
                portrait = config['default_portrait'])
u.save()

token = tables.Session.make_token(u)
url   = tables.Session.make_token_url(token, config['site_url'])

s = tables.Session(user      = u.id,
                   sessionid = token)
s.save()

for room in config['public_rooms']:
    r = tables.Room(owner  = u.id,
                    public = True,
                    name   = room)
    r.save()
    f = tables.Folder(name = room,
                      room = r.id,
                      owner = u.id,
                      public = True,
                      parent = None)
    f.save()

u.join_public()
u.commit()

print("Database Created.")
print("login url: "+url)
